module.exports = {
  CONTACT_INFO: 'CONTACT_INFO',
  CALLER_NAME: 'CALLER_NAME',
  CALL_UPLOAD: 'CALL_UPLOAD',
  CREATE_CONTACT: 'CREATE_CONTACT',
  CREATE_LEAD: 'CREATE_LEAD',
  LIST_USERS: 'LIST_USERS',
  COMMENT_CALL: 'COMMENT_CALL',
  HTTP_ACTION: 'HTTP_ACTION'
}
